### PR TITLE
Send info and error messages in a different thread that doesn't block…

### LINKED ISSUE #2: Don't block non-promt conversations services while another service is promting
# Test setup
In order to authenticate to `su` suing password OR fingerprint I used the following setup.
Relevant contents of `/etc/pam.d/su`:
```
[...]
auth            required        pam_any.so {"any-fingerprint": "Fingerprint", "any-password": "Password"}
[...]
```

Content of `/etc/pam.d/any-fingerprint`:
```
auth            required        pam_fprintd.so
account         required        pam_permit.so
```

Content of `/etc/pam.d/any-password`:
```
auth            required        pam_unix.so
account         required        pam_permit.so
```

# Problem description
When trying to authenticate using a fingerprint, the authentication does not succeed until a (invalid/empty) password is provided as shown here:
```
$ pamtester su skruppy authenticate
[Password] Password: 
[Fingerprint] Place your right index finger on the fingerprint reader
pamtester: successfully authenticated
```

# Cause of the issue
This is caused by `pam_unix` always being faster asking for a password than `pam_fprintd` wanting to print some [informational notices](https://gitlab.freedesktop.org/libfprint/fprintd/-/blob/master/pam/pam_fprintd.c#L300).
Due to the mutex placed on the upstream conversation, the progress of `pam_fprintd` is halted at the output request of the info message until an user input has been provided to `pam_unix`.
Hence the `pam_fprintd` module never returns any result before `pam_unix`.

# Possible solutions
## Reply non-promt requests from queue
For non `promt_*` calls like `info()` or `error()` add them to a queue during an ongoing promt-call and reply them once the promt is done.

## Combine non-promt requests
For non `promt_*` calls like `info()` or `error()` collect the messages in a single concatenated message during an ongoing promt-call. Send this concatenated message once the promt-call has finished.

This has the advantage that GUIs  which might only show a single message at a time do not only show the last queued message, but all of them.

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
Fixes #2 
@Skruppy can you review this?

### CODE REVIEW

**Comment by skruppy** [comment]
In my first test I authenticated only using fingerprint:
```
$ pamtester su skruppy authenticate
Input: {"modules": {"any-fingerprint": "Fingerprint", "any-password": "Password"}, "mode": "One"}
Input: Input {
    mode: One,
    modules: {
        "any-password": "Password",
        "any-fingerprint": "Fingerprint",
    },
}
[Password] Password: pamtester: successfully authenticated
$ [... no input is echoed beyond this point ...]
```
So, the authentication itself worked, but afterwards no key press was visible.
This is probably because the conv callback of the tester disabled input echoing in order to secretly read the password from the user but was not able to restore the terminal echo settings because it was canceled by the successful result of the fingerprint authentication.

I guess the issue here is that PAM is [not rely thread-save](https://man7.org/linux/man-pages/man3/pam.3.html#:~:text=The%20libpam%20interfaces%20are%20only%20thread%2Dsafe%20if%20each%20thread%20within%0A%20%20%20%20%20%20%20the%20multithreaded%20application%20uses%20its%20own%20PAM%20handle.) but you are calling the conversation from different threads.
I guess you have to do all the conversation from the main thread.
The bad news is, that this entails that I always have to enter an empty password, even if I only want to authenticate using fingerprint :/

On the upside, I found that pam_conv can handle [multiple messages at once](https://linux.die.net/man/3/pam_conv#:~:text=is%20to%20say%2C-,num_msg,-holds%20the%20length), so no need to combine the queued messages during a blocking promt call.

**Comment by ChocolateLoverRaj** [comment]
> The libpam interfaces are only thread-safe if each thread within
       the multithreaded application uses its own PAM handle.
       
So that means that this PAM module is a hack. That's ok I guess.

For handling multiple messages at once then the underlying library https://github.com/anowell/pam-rs would need to implement multiple messages at once.

**Comment by skruppy** [comment]
I guess it's not the underlying library pam-rs here to blame, because this one just passes the calls on to whatever software instantiated the PAM stack (like sudo or GDM) and they in turn just adhere to the API specification.

So maybe what one could do is to extend the loop you already have where you wait for the authentication results and also allow receiving of those four message types through the same channel.
They are then picked up one after another in the main thread (and not in parallel threads) and send using `conv.send`.

The sub PAM stacks running in the threads all have their own PamAnyConversation which just forwards all the messages to the extended loop in the main thread.
Each thread also creates their own back-channel.
If a sub PAM stack forwards a proming message they also attach the sending end of the back-channel to the forwarded message.
Using this, the extended loop in the main thread can send back the result.

This gives us thread safety as well as queuing of massages and only those PAM sub stacks actually waiting for are user response are blocked.
It does not prevent that you have to enter an empty password, but at least you don't have to care about any order (you can scan your fingerprint before or after you hit enter).

**Comment by ChocolateLoverRaj** [comment]
Ideally there shouldn't be a need for pressing enter after unlocking with fingerprint. I wonder if there is a way of doing this without messing up typing in the terminal.

**Comment by ChocolateLoverRaj** [comment]
@skruppy what are the uses for this pam module (see #7)? I'm thinking of possibly replacing the `sudo` command with something that runs multiple PAMs in parallel so we don't need to do anything hacky.

**Comment by skruppy** [comment]
From the documentation of `sudo`, `su` and `doas`, I couldn't figure out a way to use multiple PAM stacks in parallel.
Also on the graphical DM side I only found GDM being able to use multiple PAM stacks.

Looking into how https://gitlab.com/mishakmak/pam-fprint-grosshack solves this problem: They just restore the terminal settings before they return to undo the password entry settings. But this is then only a hacky solution for terminal applications and not for example LightDM.

**Comment by ChocolateLoverRaj** [comment]
I think the "grosshack" method is actually pretty good. Maybe this program should have an option to choose between two modes.
- "Grosshack" mode
- Empty prompt mode - close a prompt by entering anything into it and if a different authentication module succeeds then `pam-any` will succeed.

**Comment by ChocolateLoverRaj** [comment]
I'm going to merge this with "gross hack" mode. We can add a non-hack mode and fix #3 along with it.

**Pull request merged**
