### PR TITLE
Add installation instructions

### LINKED ISSUE #10: Instructions please?
hey, Just want to setup this with Howdy. could you please provide just a little instructions as to what should I do? or where do the files go? I know somethings but as they say little knowledge is worse than no knowledge. So could you please provide some instructions to set this up!

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
Fixes #10

### CODE REVIEW

**Comment by alba4k** [comment]
Why isn't this merged?

**Comment by alba4k** [comment]
That was fast, lol

by the way, @ChocolateLoverRaj , would you recommend using this? is it safe / done as it is? if so, I wouldn't mind creating an aur package for it if it's fine by you

**Comment by ChocolateLoverRaj** [comment]
> @ChocolateLoverRaj , would you recommend using this?

I would recommend using this if people want to run PAM modules in parallel within a single PAM module (such as for sudo authentication). If they can directly run multiple PAM modules in their own code, such as what KDE and GDM do for lock screens, that would be better.



> is it safe

It is hacky. See #3. Kind of like `[pam-fprint-grosshack](https://gitlab.com/mishakmak/pam-fprint-grosshack)`



> done as it is?

Yes. It is ready to be used.

> if so, I wouldn't mind creating an aur package for it if it's fine by you

That is fine with me. If you want you can add one of those tables of packaging status to the README too.

**Comment by alba4k** [comment]
I would be fine with it being like fprint-grosshack, as that is what I was using before. Will wait for some extra insight into #12 before adding this to the AUR

Wouldn't make a packaging tablet like that, just mention that it is avaiable as an aur package. also, is there any reason why the file name is `libpam_any.so` and not `pam_any.so`? is that how things are on fedora? I would likely rename it to `pam_any.so` on arch if there is no reason to keep it otherwise

immagine

**Comment by ChocolateLoverRaj** [comment]
> is there any reason why the file name is `libpam_any.so` and not `pam_any.so`?

It's just the default Rust output file name. Probably caused by https://github.com/ChocolateLoverRaj/pam-any/blob/e77687709d092a6bb77e57a444403798855075c0/Cargo.toml#L7. This can be changed.

**Comment by alba4k** [comment]
Check what fedora uses for that kind of stuff first I guess, but otherwise sure

**Pull request merged**
